### ISSUE TITLE
ImapGmailClient no longer working

### ISSUE THREAD

**Issue by hypermunkee** [spajus/gmail4j#3]
No Gmail4j method calls are working for me anymore...

com.googlecode.gmail4j.GmailException: ImapGmailClient failed marking all GmailMessage as read
    at com.googlecode.gmail4j.javamail.ImapGmailClient.markAllAsRead(ImapGmailClient.java:340)

com.googlecode.gmail4j.GmailException: Failed getting unread messages
    at com.googlecode.gmail4j.javamail.ImapGmailClient.getUnreadMessages(ImapGmailClient.java:185)

Everything was working fine as recently as last week. Do you know if something has changed? Is anyone else encountering this issue?

Thanks!
Andrew

**Comment by hypermunkee** [comment]
Sorry, bogus issue. Turns out someone in our org changed all the account passwords...
